# Specify a base image
# node we found from hub docker
FROM node:alpine

WORKDIR '/app'

# Install some depenendencies
COPY package.json .
RUN npm install
COPY . .

# Default command
CMD ["npm", "run", "start"]
